export const transactions = [
  {
    id: 1,
    type: "received",
    amount: 2500.0,
    description: "Salary Payment",
    date: "2024-12-15",
    time: "09:30 AM",
    aiInsight: "Regular income pattern verified - Low risk",
    category: "Income",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "TechCorp Inc.",
    location: "New York, NY",
    reference: "PAY-2024-001",
  },
  {
    id: 2,
    type: "sent",
    amount: 89.99,
    description: "Netflix Subscription",
    date: "2024-12-14",
    time: "08:15 PM",
    aiInsight: "Recurring merchant - Behavioral pattern normal",
    category: "Entertainment",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "Netflix",
    location: "Online",
    reference: "SUB-2024-002",
  },
  {
    id: 3,
    type: "sent",
    amount: 450.0,
    description: "BestBuy Purchase",
    date: "2024-12-13",
    time: "02:45 PM",
    aiInsight: "New merchant detected - Location verified",
    category: "Shopping",
    securityStatus: "flagged",
    riskLevel: "medium",
    merchant: "Best Buy",
    location: "Los Angeles, CA",
    reference: "PUR-2024-003",
  },
  {
    id: 4,
    type: "received",
    amount: 1200.0,
    description: "Freelance Project",
    date: "2024-12-12",
    time: "11:20 AM",
    aiInsight: "Unusual amount - Biometric verification passed",
    category: "Income",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "Digital Agency",
    location: "Remote",
    reference: "PROJ-2024-004",
  },
  {
    id: 5,
    type: "sent",
    amount: 75.5,
    description: "Grocery Shopping",
    date: "2024-12-11",
    time: "06:30 PM",
    aiInsight: "Regular spending pattern - Geolocation confirmed",
    category: "Food",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "Whole Foods",
    location: "San Francisco, CA",
    reference: "GRO-2024-005",
  },
  {
    id: 6,
    type: "sent",
    amount: 1250.0,
    description: "Wire Transfer",
    date: "2024-12-10",
    time: "03:15 PM",
    aiInsight: "Suspicious pattern detected - Transaction blocked",
    category: "Transfer",
    securityStatus: "blocked",
    riskLevel: "high",
    merchant: "Unknown",
    location: "Unknown",
    reference: "WIRE-2024-006",
  },
  {
    id: 7,
    type: "sent",
    amount: 25.0,
    description: "Coffee Shop",
    date: "2024-12-10",
    time: "08:45 AM",
    aiInsight: "Regular merchant - Safe transaction",
    category: "Food",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "Starbucks",
    location: "San Francisco, CA",
    reference: "CAF-2024-007",
  },
  {
    id: 8,
    type: "sent",
    amount: 120.0,
    description: "Gas Station",
    date: "2024-12-09",
    time: "07:20 AM",
    aiInsight: "Routine fuel purchase - Location verified",
    category: "Transportation",
    securityStatus: "verified",
    riskLevel: "low",
    merchant: "Shell",
    location: "San Francisco, CA",
    reference: "GAS-2024-008",
  },
];
